[platformio]
default_envs = esp8266, esp32s3

[env]
framework = arduino
monitor_speed = 115200
build_flags = 
    -DPIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY
    -DVTABLES_IN_FLASH
    -DESP_ARDUINO_LUA_SUPPORT
lib_deps = 
    ringbuffer
    pubsubclient
    bblanchon/ArduinoJson@^7.0.0
    milesburton/DallasTemperature@^3.11.0
    paulstoffregen/OneWire@^2.3.8
    adafruit/Adafruit NeoPixel@^1.12.0

[env:esp8266]
platform = espressif8266
board = d1_mini
board_build.flash_mode = dio
board_build.ldscript = eagle.flash.4m2m.ld
build_flags = 
    ${env.build_flags}
    -DESP8266
    -Wl,-Teagle.flash.4m2m.ld

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
board_build.partitions = min_spiffs.csv
board_build.arduino.memory_type = qio_opi
build_flags = 
    ${env.build_flags}
    -DESP32
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1